# Generated by Django 5.1.6 on 2025-03-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_bus_driver_route_buslocation_bus_driver_bus_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='stops',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='route',
            name='timings',
            field=models.JSONField(default=list),
        ),
    ]
