# Generated by Django 5.1.6 on 2025-04-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_alter_route_stops_alter_route_timings'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
