# Generated by Django 5.1.6 on 2025-04-25 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_route_latitude_route_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.route'),
        ),
        migrations.AddField(
            model_name='student',
            name='stop_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
