# Generated by Django 5.1.6 on 2025-04-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_student_route_student_stop_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='route',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='route',
            name='stops_latitudes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='route',
            name='stops_longitudes',
            field=models.JSONField(default=list),
        ),
    ]
